version: '3.4'

services:
  trlogictask:
    image: trlogictask:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\EweioPC\source\repos\TRLogicTask\TRLogicTask:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

