version: '3.4'

services:
  sql-server:
      image: microsoft/mssql-server-windows-express
      environment:
       SA_PASSWORD: DockerCon2017
       ACCEPT_EULA: Y
       NAME: sql-server

  trlogictask:
    image: ${DOCKER_REGISTRY}trlogictask
    build:
      context: .\TRLogicTask
      dockerfile: Dockerfile